name: Add PRs to the new Hunger Games GitHub Project

on:
  - pull_request_target

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/40
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT || github.token }}
          label-operator: AND
